### PR TITLE
Reduce object allocations and CPU overhead.

### PR DESCRIPTION
**Pull request by zachary-kuhn**
## Why?
- This is a performance optimization so it doesn't burn so much CPU
## What Changed?
- I reduced the number of allocations happening during a tight loop, which is the biggest hot spot in the code. Two things were happening here. First, object allocations puts pressure on the garbage collector. Second, when you call `new convnetjs.Vol(1, 1, this.net_inputs);`, it produces a random number for `1x1xthis.net_inputs` number of times. This ends up being very computationally expensive. I profiled this and it was taking 60% of the CPU, but this reduces it way down.

### CODE REVIEW

**Comment by keeganbrown** [comment]
Nice! This is actually a supplemental file that is part of auxilary materials with ConvnetJS; as such I've been avoiding changing this like I avoid the flu. I just want to ensure that the neural net values get updated properly with this code in there (I've seen it act funny in strange ways before, without complaining), but if that's all good, then I'll give you a thumbs up. Thanks for contributing!

**Comment by zachary-kuhn** [comment]
Ah, let me dig a little more in the library's code. I already checked the `Vol` constructor and it doesn't do anything weird. But I need to check the other places it gets passed to make sure there are no mutations.

**Comment by zachary-kuhn** [comment]
OK, I cannot say with any guarantees that this behaves the same. There are a few layers which potentially mutate the values. Let me take a second swing at this that will save CPU time by not calculating randoms every time, but will still have the same number of new object allocations.

**Comment by zachary-kuhn** [comment]
So now we only have to worry about this piece of code:

```
function(sx, sy, depth, c) {
  // this is how you check if a variable is an array. Oh, Javascript :)
  if(Object.prototype.toString.call(sx) === '[object Array]') {
    // we were given a list in sx, assume 1D volume and fill it up
    this.sx = 1;
    this.sy = 1;
    this.depth = sx.length;
    // we have to do the following copy because we want to use
    // fast typed arrays, not an ordinary javascript array
    this.w = global.zeros(this.depth);
    this.dw = global.zeros(this.depth);
    for(var i=0;i<this.depth;i++) {
      this.w[i] = sx[i];
    }
  } else {
    // we were given dimensions of the vol
    this.sx = sx;
    this.sy = sy;
    this.depth = depth;
    var n = sx*sy*depth;
    this.w = global.zeros(n);
    this.dw = global.zeros(n);
    if(typeof c === 'undefined') {
      // weight normalization is done to equalize the output
      // variance of every neuron, otherwise neurons with a lot
      // of incoming connections have outputs of larger variance
      var scale = Math.sqrt(1.0/(sx*sy*depth));
      for(var i=0;i<n;i++) { 
        this.w[i] = global.randn(0.0, scale);
      }
    } else {
      for(var i=0;i<n;i++) { 
        this.w[i] = c;
      }
    }
  }
}
```

We see here the big difference is we do not call `global.randn` a bunch of times only to have `w` reassigned anyways. `global.randn` calls `gaussRandom`, which is the expensive operation that burns up CPU time. I feel confident this solution gives us the same outcomes as before the change but with much fewer wasted computations.

**Comment by keeganbrown** [comment]
@zachary-kuhn You're a saint for combing through all that junk. (you can tell the author of the library isn't a JS engineer eh?). I'm game to merge this in and keep an eye on whether or not it's learning. I triple checked your logic and it seems sound. So +1, lets see what this does.

**Comment by keeganbrown** [comment]
@zachary-kuhn just fyi, we're holding on merging this branch until after SB3 launches. In lieu of a real solution, we're throttling the learning more.

**Comment by zachary-kuhn** [comment]
Thanks for the update! Yeah, as much as I want to be like "this delay makes me ANGRY 😠," I'm totally ok with it.

**Pull request merged**
